modified README and install script. renamed folders. added pythong __init__.py files so can act as a module. did't yet test any of install script modifications.

diff --git a/rp2so b/rp2so
--- a/rp2so
+++ b/rp2so
@@ -1,43 +1,62 @@
-#! /bin/bash
+#!/bin/bash
 
-#use WINE to install refprop.exe in the C:\Program Files\REFPROP\ directory
-#execute this binery file, need to have the following installed on Linux:
+#first use WINE to install refprop.exe in the C:\Program Files\REFPROP\ directory
+#then execute this shell script
+#note, you will need to have the following installed on Linux:
 #	gfortran
 #	sed
 #	dos2unix
-#use the refprop.py interface to call the librefprop.so
+#finally, you can then use the refprop.py interface to call the librefprop.so
 
-#define standard path where the original refprop files will be stored
-path='/usr/local/lib/refprop/'
+#cause the script to abort immediately on error instead of trying to continue
+#an error could for example be caused by not running this script as superuser (sudo), if installing to a path that requires superuser permissions
+set -e
 
-#delete previous trail
-sudo rm -rf ${path}
-sudo rm -f ${path%refprop/}librefprop*
+
+echo
+echo "enter the path where the REFPROP files were installed to, or just hit enter for ~/.wine/drive_c/Program\ Files/REFPROP/"
+read REFPROPSourcePath;
+if [ "$REFPROPSourcePath" == "" ]; then
+	REFPROPSourcePath='~/.wine/drive_c/Program\ Files/REFPROP/'
+fi;
+
+
+echo
+echo "enter base path where the refprop files will be installed to, or just hit enter for /usr/local/lib/refprop/"
+echo 'Warning: You may need to be running this script as superuser (i.e. "sudo ./rp2so") for /usr/local/lib/refprop/ . you can press control-c to stop the script now'
+read path;
+if [ "$path" == "" ]; then
+	path='/usr/local/lib/refprop/'
+fi;
+
+#delete previous installation
+rm -rf ${path}
+rm -f ${path%refprop/}librefprop*
 
 #create directories
-sudo mkdir -p ${path}FOR/
-sudo mkdir -p ${path}fluids/
-sudo mkdir -p ${path}mixtures/
+mkdir -p ${path}FOR/
+mkdir -p ${path}fluids/
+mkdir -p ${path}mixtures/
 
 #copy fortran / refprop files to ${path}
-sudo cp -r ~/.wine/drive_c/Program\ Files/REFPROP/fortran/*.FOR ${path}FOR/
-sudo cp -r ~/.wine/drive_c/Program\ Files/REFPROP/fluids/* ${path}fluids/
-sudo cp -r ~/.wine/drive_c/Program\ Files/REFPROP/mixtures/* ${path}mixtures/
+cp -r $REFPROPSourcePath/fortran/*.FOR ${path}FOR/
+cp -r $REFPROPSourcePath/fluids/* ${path}fluids/
+cp -r $REFPROPSourcePath/mixtures/* ${path}mixtures/
 
 #allow read permission all
-sudo chmod -R a+r ${path}fluids/
-sudo chmod -R a+r ${path}mixtures/
+chmod -R a+r ${path}fluids/
+chmod -R a+r ${path}mixtures/
 
 #rename all filenames to UPPERCASE
 echo 'rename lowercase to UPPERCASE filenames'
 cd ${path}fluids/
-sudo rename 'y/a-z/A-Z/' *
+rename 'y/a-z/A-Z/' *
 cd ${path}mixtures/
-sudo rename 'y/a-z/A-Z/' *
+rename 'y/a-z/A-Z/' *
 
 #modify PASS_FTN.FOR
 #remove windows specific command
-sudo sed -i 's/      dll_export/c     dll_export/' ${path}FOR/PASS_FTN.FOR
+sed -i 's/      dll_export/c     dll_export/' ${path}FOR/PASS_FTN.FOR
 
 #process files (dos to unix)
 for files in ${path}FOR/*.FOR ${path}fluids/* ${path}mixtures/*
@@ -45,7 +64,7 @@ do
 	{
 	echo "processing ${files}"
 	#change *.FOR files from dos to unix
-	sudo dos2unix -q ${files}
+	dos2unix -q ${files}
 	} &
 done
 #wait for multiprocessing to complete
@@ -53,23 +72,24 @@ wait
 
 #create object file
 echo 'create object files'
-sudo mkdir -p /tmp/refprop/object
+mkdir -p /tmp/refprop/object
 cd /tmp/refprop/object
-sudo gfortran -fpic -c -g ${path}FOR/*.FOR
+gfortran -fpic -c -g ${path}FOR/*.FOR
 
 #create the dynamically link "shared objects" (so) library
 echo 'create shared object file'
-sudo gfortran -shared -Wl,-soname,librefprop.so.9 -o ${path}librefprop.so.9.0 /tmp/refprop/object/*.o -lc
+gfortran -shared -Wl,-soname,librefprop.so.9 -o ${path}librefprop.so.9.0 /tmp/refprop/object/*.o -lc
 
-#delete object files
-cd ~
-sudo rm -rf /tmp/refprop/
+#first get out of the folder that is going to be deleted
+cd
+#then delete temporary object files
+rm -rf /tmp/refprop/
 
 #install the object file
 echo 'install object file'
-sudo ldconfig -n ${path%/}
-sudo ln -s ${path}librefprop.so.9 ${path%refprop/}librefprop.so
+ldconfig -n ${path%/}
+ln -s ${path}librefprop.so.9 ${path%refprop/}librefprop.so
 
-#display ported commands
-#nm ${path}librefprop.so
+echo
+echo "If you want to display ported commands, type: nm ${path}librefprop.so"
 
